// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestService.Model;

namespace RestService.Migrations
{
    [DbContext(typeof(CarContext))]
    [Migration("20190630144344_TestMgr1")]
    partial class TestMgr1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RestService.Model.Cars", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MarkName");

                    b.Property<string>("ModelName");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.ToTable("Tbl_MyCars");

                    b.HasData(
                        new { Id = 1, MarkName = "Mercedes", ModelName = "G55", Year = 2016 },
                        new { Id = 2, MarkName = "Nissan", ModelName = "X-terra", Year = 2003 },
                        new { Id = 3, MarkName = "Toyota", ModelName = "Land Crouiser 200", Year = 2018 },
                        new { Id = 4, MarkName = "Dayhatcu", ModelName = "Bqumba", Year = 1985 }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
