//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exibition
    {
        public int ExibitionId { get; set; }
        public int ArtFactId { get; set; }
        public System.DateTime ExibitionDate { get; set; }
        public string ExibitionPleaceName { get; set; }
        public string EventName { get; set; }
        public Nullable<int> Sponsor { get; set; }
    
        public virtual SponsorInfo SponsorInfo { get; set; }
    }
}
